# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!
# use_modular_headers!
# use_frameworks! :linkage => :static
# source 'https://cdn.cocoapods.org/'
# source 'https://github.com/cleveradssolutions/CAS-Specs.git'

# $RNFirebaseAnalyticsWithoutAdIdSupport=true
# # $RNFirebaseAsStaticFramework = true

# # Отключение Flipper
# # flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'wallpapers' do
#   config = use_native_modules!
#   pod 'CleverAdsSolutions-SDK/Optimal', '3.6.1'

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # Отключение Flipper
#     # :flipper_configuration => flipper_config,
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   target 'wallpapersTest' do
#     inherit! :complete
#     # Pods for testing
#   end

#   post_install do |installer|
#     # Убедитесь, что вызов post_install hook не вызывает ошибок
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false
#     )
#   end
# end


# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
use_modular_headers!
use_frameworks! :linkage => :static
source 'https://cdn.cocoapods.org/'
source 'https://github.com/cleveradssolutions/CAS-Specs.git'

$RNFirebaseAnalyticsWithoutAdIdSupport=true
# $RNFirebaseAsStaticFramework = true

# Отключение Flipper
# flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Измените имя цели на существующую, например, AwesomeProject
target 'AwesomeProject' do
  config = use_native_modules!
  pod 'CleverAdsSolutions-SDK/Optimal', '3.6.1'

  use_react_native!(
    :path => config[:reactNativePath],
    # Отключение Flipper
    # :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AwesomeProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Убедитесь, что вызов post_install hook не вызывает ошибок
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
